using System;

namespace NetFramework
{
    class Quiz4
    {
        static void Main(string[] args)
        {
            // Select correct here
            int index = -1;

            string question = "What is IL code?";
            string answer = "";

            if (index == 0)
                answer = "- International Code, common choice if you want to write international programs.";

            if (index == 1)
                answer = "- Intermediate Code, generated by Just In Time compiler and prepared for the execution by processor.";

            if (index == 2)
                answer = "- Intermediate Code, generated by C# compiler and packaged in ProgramName.exe or ProgramName.dll";

            if (index == 3)
                answer = "- Intermediate Code, which is generated by CLR.";

            Console.WriteLine(question);
            Console.WriteLine(answer);
        }
    }
}
